{
  "sources": [
    {"name": "The Daily Star - Business", "url": "https://www.thedailystar.net/business/rss.xml", "lang": "en", "priority": 1, "category": "business"},
    {"name": "The Daily Star - Economy", "url": "https://www.thedailystar.net/business/economy/rss.xml", "lang": "en", "priority": 1, "category": "economy"},
    {"name": "The Business Standard", "url": "https://www.tbsnews.net/rss.xml", "lang": "en", "priority": 1, "category": "business"},
    {"name": "The Financial Express", "url": "https://thefinancialexpress.com.bd/feed", "lang": "en", "priority": 1, "category": "business"},
    {"name": "bdnews24 - Business", "url": "https://bdnews24.com/business/rss.xml", "lang": "en", "priority": 1, "category": "business"},
    {"name": "bdnews24 - Economy", "url": "https://bdnews24.com/economy/rss.xml", "lang": "en", "priority": 1, "category": "economy"},
    {"name": "Dhaka Tribune - Business", "url": "https://www.dhakatribune.com/articles/business/rss.xml", "lang": "en", "priority": 1, "category": "business"},
    {"name": "Dhaka Tribune - Economy", "url": "https://www.dhakatribune.com/articles/economy/rss.xml", "lang": "en", "priority": 1, "category": "economy"},
    {"name": "United News of BD - Business", "url": "https://unb.com.bd/category/16/Business/rss", "lang": "en", "priority": 2, "category": "business"},
    {"name": "Daily Sun - Business", "url": "https://daily-sun.com/online/business/rss.xml", "lang": "en", "priority": 2, "category": "business"},
    {"name": "The Bangladesh Today", "url": "https://bangladeshtoday.net/feed", "lang": "en", "priority": 2, "category": "general"},
    {"name": "Business News Bangladesh", "url": "https://businessnews-bd.net/feed", "lang": "en", "priority": 2, "category": "business"},
    {"name": "Energy Bangla", "url": "https://energybangla.com/feed", "lang": "en", "priority": 1, "category": "energy"},
    {"name": "BIDA - Investment News", "url": "https://bida.gov.bd/investment-news/feed", "lang": "en", "priority": 1, "category": "policy"},
    {"name": "Bangladesh Sangbad Sangstha", "url": "https://bssnews.net/feed", "lang": "en", "priority": 2, "category": "general"},
    {"name": "The Asian Age", "url": "https://dailyasianage.com/feed", "lang": "en", "priority": 2, "category": "general"},
    {"name": "Economic Times - Bangladesh", "url": "https://economictimes.indiatimes.com/rssfeeds/1893352.cms", "lang": "en", "priority": 2, "category": "economy"},
    {"name": "Nikkei Asia - South Asia", "url": "https://asia.nikkei.com/rss/politics/south-asia.rss", "lang": "en", "priority": 2, "category": "business"},
    {"name": "WION - Bangladesh", "url": "https://www.wionews.com/bangladesh/rss.xml", "lang": "en", "priority": 2, "category": "general"},
    {"name": "News18 - Bangladesh", "url": "https://www.news18.com/topics/bangladesh/rss", "lang": "en", "priority": 2, "category": "general"},
    {"name": "The Dhaka Post", "url": "https://thedhakapost.com/rss.xml", "lang": "en", "priority": 2, "category": "general"},
    {"name": "Ajker Patrika", "url": "https://ajkerpatrika.com/feed", "lang": "bn", "priority": 2, "category": "general"},
    {"name": "Jagonews24", "url": "https://jagonews24.com/rss.xml", "lang": "bn", "priority": 2, "category": "general"},
    {"name": "Bangladesh Diplomat", "url": "https://bangladeshdiplomat.com/feed", "lang": "en", "priority": 2, "category": "general"},
    {"name": "Midway Securities", "url": "https://midwaybd.com/2/feed", "lang": "en", "priority": 2, "category": "stocks"},
    {"name": "TBS - Stocks", "url": "https://www.tbsnews.net/economy/stocks/rss.xml", "lang": "en", "priority": 2, "category": "stocks"},
    {"name": "Business Bangladesh", "url": "https://businessbangladesh.com.bd/feed", "lang": "en", "priority": 2, "category": "business"},
    {"name": "Dhaka Tribune - Technology", "url": "https://www.dhakatribune.com/articles/technology/rss.xml", "lang": "en", "priority": 2, "category": "tech"},
    {"name": "bdnews24 - Technology", "url": "https://bdnews24.com/technology/rss.xml", "lang": "en", "priority": 2, "category": "tech"},
    {"name": "BSS - Science & Tech", "url": "https://bssnews.net/news/science-&-technology/rss", "lang": "en", "priority": 2, "category": "tech"},
    {"name": "Daily Bangladesh - IT", "url": "https://daily-bangladesh.com/information-technology/rss.xml", "lang": "bn", "priority": 2, "category": "tech"},
    {"name": "The Dhaka Post - Tech", "url": "https://thedhakapost.com/tech/rss.xml", "lang": "bn", "priority": 2, "category": "tech"},
    {"name": "Jago News 24 - Tech", "url": "https://jagonews24.com/technology/rss.xml", "lang": "bn", "priority": 2, "category": "tech"},
    {"name": "Dhaka Tribune - Health", "url": "https://www.dhakatribune.com/articles/health/rss.xml", "lang": "en", "priority": 2, "category": "health"},
    {"name": "Financial Express - Health", "url": "https://thefinancialexpress.com.bd/health/feed", "lang": "en", "priority": 2, "category": "health"},
    {"name": "FE - First Page", "url": "https://today.thefinancialexpress.com.bd/first-page/feed", "lang": "en", "priority": 1, "category": "business"},
    {"name": "TBS - Economy", "url": "https://www.tbsnews.net/economy/rss.xml", "lang": "en", "priority": 1, "category": "economy"},
    {"name": "TBS - Bangladesh", "url": "https://www.tbsnews.net/bangladesh/rss.xml", "lang": "en", "priority": 1, "category": "general"},
    {"name": "TBS - Policy", "url": "https://www.tbsnews.net/policy/rss.xml", "lang": "en", "priority": 1, "category": "policy"},
    {"name": "TBS - Trade", "url": "https://www.tbsnews.net/trade/rss.xml", "lang": "en", "priority": 1, "category": "trade"},
    {"name": "TBS - Industry", "url": "https://www.tbsnews.net/industry/rss.xml", "lang": "en", "priority": 1, "category": "industry"},
    {"name": "TBS - Energy", "url": "https://www.tbsnews.net/energy/rss.xml", "lang": "en", "priority": 1, "category": "energy"},
    {"name": "TBS - Stock", "url": "https://www.tbsnews.net/stock/rss.xml", "lang": "en", "priority": 2, "category": "stocks"},
    {"name": "The Daily Star - Trade", "url": "https://www.thedailystar.net/business/trade/rss.xml", "lang": "en", "priority": 1, "category": "trade"},
    {"name": "The Daily Star - Industry", "url": "https://www.thedailystar.net/business/industries/rss.xml", "lang": "en", "priority": 1, "category": "industry"},
    {"name": "The Daily Star - Stock", "url": "https://www.thedailystar.net/business/stock/rss.xml", "lang": "en", "priority": 2, "category": "stocks"},
    {"name": "FE - Economy", "url": "https://thefinancialexpress.com.bd/economy/feed", "lang": "en", "priority": 1, "category": "economy"},
    {"name": "FE - Trade", "url": "https://thefinancialexpress.com.bd/trade/feed", "lang": "en", "priority": 1, "category": "trade"},
    {"name": "FE - Industry", "url": "https://thefinancialexpress.com.bd/industry/feed", "lang": "en", "priority": 1, "category": "industry"},
    {"name": "FE - Stock", "url": "https://thefinancialexpress.com.bd/stock/feed", "lang": "en", "priority": 2, "category": "stocks"},
    {"name": "Dhaka Tribune - National", "url": "https://www.dhakatribune.com/articles/national/rss.xml", "lang": "en", "priority": 2, "category": "general"},
    {"name": "Dhaka Tribune - Politics", "url": "https://www.dhakatribune.com/articles/politics/rss.xml", "lang": "en", "priority": 2, "category": "policy"},
    {"name": "Dhaka Tribune - World", "url": "https://www.dhakatribune.com/articles/world/rss.xml", "lang": "en", "priority": 2, "category": "general"},
    {"name": "bdnews24 - National", "url": "https://bdnews24.com/national/rss.xml", "lang": "en", "priority": 2, "category": "general"},
    {"name": "bdnews24 - Politics", "url": "https://bdnews24.com/politics/rss.xml", "lang": "en", "priority": 2, "category": "policy"},
    {"name": "bdnews24 - World", "url": "https://bdnews24.com/world/rss.xml", "lang": "en", "priority": 2, "category": "general"},
    {"name": "SUN News Bangladesh", "url": "https://en.sunnews24x7.com/rss", "lang": "en", "priority": 2, "category": "general"},
    {"name": "Prothom Alo - Business", "url": "https://en.prothomalo.com/feed/business", "lang": "en", "priority": 1, "category": "business"},
    {"name": "Prothom Alo - Economy", "url": "https://en.prothomalo.com/feed/economy", "lang": "en", "priority": 1, "category": "economy"},
    {"name": "New Age - Business", "url": "https://www.newagebd.net/feed/business", "lang": "en", "priority": 2, "category": "business"},
    {"name": "New Age - Economy", "url": "https://www.newagebd.net/feed/economy", "lang": "en", "priority": 2, "category": "economy"}
  ]
}
